/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v10.0
processor: MKL46Z256xxx4
package_id: MKL46Z256VLL4
mcu_data: ksdk2_0
processor_version: 10.0.0
board: FRDM-KL46Z
pin_labels:
- {pin_num: '35', pin_signal: TSI0_CH2/PTA1/UART0_RX/TPM2_CH0, label: 'J1[2]/D0/UART1_RX_TGTMCU', identifier: DEBUG_UART_RX;T8}
- {pin_num: '36', pin_signal: TSI0_CH3/PTA2/UART0_TX/TPM2_CH1, label: 'J1[4]/D1/UART1_TX_TGTMCU', identifier: DEBUG_UART_TX;T7}
- {pin_num: '96', pin_signal: LCD_P43/PTD3/SPI0_MISO/UART2_TX/TPM0_CH3/SPI0_MOSI/LCD_P43_Fault, label: 'J1[6]/D2', identifier: T6}
- {pin_num: '42', pin_signal: PTA12/TPM1_CH0/I2S0_TXD0, label: 'J1[8]/D3', identifier: T5}
- {pin_num: '38', pin_signal: TSI0_CH5/PTA4/I2C1_SDA/TPM0_CH1/NMI_b, label: 'J1[10]/D4', identifier: T4}
- {pin_num: '39', pin_signal: PTA5/USB_CLKIN/TPM0_CH2/I2S0_TX_BCLK, label: 'J1[12]/D5', identifier: T3}
- {pin_num: '85', pin_signal: LCD_P29/CMP0_IN3/PTC9/I2C0_SDA/TPM0_CH5/I2S0_RX_BCLK/LCD_P29_Fault, label: 'J1[16]/D7', identifier: T1}
- {pin_num: '1', pin_signal: LCD_P48/PTE0/SPI1_MISO/UART1_TX/RTC_CLKOUT/CMP0_OUT/I2C1_SDA/LCD_P48_Fault, label: 'J2[18]/D14', identifier: TX}
- {pin_num: '2', pin_signal: LCD_P49/PTE1/SPI1_MOSI/UART1_RX/SPI1_MISO/I2C1_SCL/LCD_P49_Fault, label: 'J2[20]/D15', identifier: RX}
- {pin_num: '41', pin_signal: PTA7/TPM0_CH4, label: 'J2[5]', identifier: RS}
- {pin_num: '90', pin_signal: LCD_P36/PTC16/LCD_P36_Fault, label: 'J2[3]', identifier: RW}
- {pin_num: '89', pin_signal: LCD_P33/PTC13/TPM_CLKIN1/LCD_P33_Fault, label: 'J2[1]', identifier: E}
- {pin_num: '87', pin_signal: LCD_P31/PTC11/I2C1_SDA/I2S0_RXD0/LCD_P31_Fault, label: 'J1[15]/I2S_RXD', identifier: S1}
- {pin_num: '86', pin_signal: LCD_P30/PTC10/I2C1_SCL/I2S0_RX_FS/LCD_P30_Fault, label: 'J1[13]/I2S_RX_FS', identifier: S2}
- {pin_num: '83', pin_signal: LCD_P27/CMP0_IN1/PTC7/SPI0_MISO/USB_SOF_OUT/I2S0_RX_FS/SPI0_MOSI/LCD_P27_Fault, label: 'J1[11]/SOF_OUT', identifier: S3}
- {pin_num: '82', pin_signal: LCD_P26/CMP0_IN0/PTC6/LLWU_P10/SPI0_MOSI/EXTRG_IN/I2S0_RX_BCLK/SPI0_MISO/I2S0_MCLK/LCD_P26_Fault, label: 'J1[9]/I2S_RX_BCLK', identifier: S4}
- {pin_num: '80', pin_signal: LCD_P24/PTC4/LLWU_P8/SPI0_PCS0/UART1_TX/TPM0_CH3/I2S0_MCLK/LCD_P24_Fault, label: 'J1[7]/I2S_MCLK', identifier: S5}
- {pin_num: '70', pin_signal: LCD_P20/ADC0_SE14/TSI0_CH13/PTC0/EXTRG_IN/USB_SOF_OUT/CMP0_OUT/I2S0_TXD0/LCD_P20_Fault, label: 'J1[5]/I2S_TXD', identifier: S6}
- {pin_num: '65', pin_signal: LCD_P15/TSI0_CH12/PTB19/TPM2_CH1/I2S0_TX_FS/LCD_P15_Fault, label: 'J1[3]/I2S_TX_FS', identifier: S7}
- {pin_num: '64', pin_signal: LCD_P14/TSI0_CH11/PTB18/TPM2_CH0/I2S0_TX_BCLK/LCD_P14_Fault, label: 'J1[1]/I2S_TX_BCLK', identifier: S8}
- {pin_num: '27', pin_signal: DAC0_OUT/ADC0_SE23/CMP0_IN4/PTE30/TPM0_CH3/TPM_CLKIN1, label: 'J4[11]/DAC_OUT', identifier: D7}
- {pin_num: '21', pin_signal: ADC0_DM3/ADC0_SE7a/PTE23/TPM2_CH1/UART2_RX, label: 'J4[7]/DIFF_ADC1_DM', identifier: D5}
- {pin_num: '19', pin_signal: LCD_P60/ADC0_DM0/ADC0_SE4a/PTE21/TPM1_CH1/UART0_RX/LCD_P60_Fault, label: 'J4[3]/DIFF_ADC0_DM', identifier: D4}
- {pin_num: '66', pin_signal: LCD_P16/PTB20/CMP0_OUT/LCD_P16_Fault, label: 'J4[9]/CMP_OUT', identifier: D6}
- {pin_num: '3', pin_signal: LCD_P50/PTE2/SPI1_SCK/LCD_P50_Fault, label: 'J3[15]', identifier: E8}
- {pin_num: '4', pin_signal: LCD_P51/PTE3/SPI1_MISO/SPI1_MOSI/LCD_P51_Fault, label: 'J3[13]', identifier: E7}
- {pin_num: '7', pin_signal: LCD_P54/PTE6/I2S0_MCLK/USB_SOF_OUT/LCD_P54_Fault, label: 'J3[11]', identifier: E6}
- {pin_num: '14', pin_signal: LCD_P55/ADC0_DP1/ADC0_SE1/PTE16/SPI0_PCS0/UART2_TX/TPM_CLKIN0/LCD_P55_Fault, label: 'J3[9]', identifier: E5}
- {pin_num: '15', pin_signal: LCD_P56/ADC0_DM1/ADC0_SE5a/PTE17/SPI0_SCK/UART2_RX/TPM_CLKIN1/LPTMR0_ALT3/LCD_P56_Fault, label: 'J3[7]', identifier: E4}
- {pin_num: '16', pin_signal: LCD_P57/ADC0_DP2/ADC0_SE2/PTE18/SPI0_MOSI/I2C0_SDA/SPI0_MISO/LCD_P57_Fault, label: 'J3[5]', identifier: E3}
- {pin_num: '17', pin_signal: LCD_P58/ADC0_DM2/ADC0_SE6a/PTE19/SPI0_MISO/I2C0_SCL/SPI0_MOSI/LCD_P58_Fault, label: 'J3[3]', identifier: E2}
- {pin_num: '28', pin_signal: PTE31/TPM0_CH4, label: 'J3[1]', identifier: E1}
- {pin_num: '92', pin_signal: LCD_P38/PTC18/LCD_P38_Fault, label: 'DS1[10]/LCD-10', identifier: LCD_10;T2}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '35', peripheral: GPIOA, signal: 'GPIO, 1', pin_signal: TSI0_CH2/PTA1/UART0_RX/TPM2_CH0, identifier: T8, direction: INPUT}
  - {pin_num: '36', peripheral: GPIOA, signal: 'GPIO, 2', pin_signal: TSI0_CH3/PTA2/UART0_TX/TPM2_CH1, identifier: T7, direction: INPUT}
  - {pin_num: '96', peripheral: GPIOD, signal: 'GPIO, 3', pin_signal: LCD_P43/PTD3/SPI0_MISO/UART2_TX/TPM0_CH3/SPI0_MOSI/LCD_P43_Fault, direction: INPUT}
  - {pin_num: '42', peripheral: GPIOA, signal: 'GPIO, 12', pin_signal: PTA12/TPM1_CH0/I2S0_TXD0, direction: INPUT}
  - {pin_num: '38', peripheral: GPIOA, signal: 'GPIO, 4', pin_signal: TSI0_CH5/PTA4/I2C1_SDA/TPM0_CH1/NMI_b, direction: INPUT}
  - {pin_num: '39', peripheral: GPIOA, signal: 'GPIO, 5', pin_signal: PTA5/USB_CLKIN/TPM0_CH2/I2S0_TX_BCLK, direction: INPUT}
  - {pin_num: '92', peripheral: GPIOC, signal: 'GPIO, 18', pin_signal: LCD_P38/PTC18/LCD_P38_Fault, identifier: T2, direction: INPUT}
  - {pin_num: '85', peripheral: GPIOC, signal: 'GPIO, 9', pin_signal: LCD_P29/CMP0_IN3/PTC9/I2C0_SDA/TPM0_CH5/I2S0_RX_BCLK/LCD_P29_Fault, direction: INPUT}
  - {pin_num: '89', peripheral: GPIOC, signal: 'GPIO, 13', pin_signal: LCD_P33/PTC13/TPM_CLKIN1/LCD_P33_Fault, direction: OUTPUT}
  - {pin_num: '90', peripheral: GPIOC, signal: 'GPIO, 16', pin_signal: LCD_P36/PTC16/LCD_P36_Fault, direction: OUTPUT}
  - {pin_num: '41', peripheral: GPIOA, signal: 'GPIO, 7', pin_signal: PTA7/TPM0_CH4, direction: OUTPUT}
  - {pin_num: '27', peripheral: GPIOE, signal: 'GPIO, 30', pin_signal: DAC0_OUT/ADC0_SE23/CMP0_IN4/PTE30/TPM0_CH3/TPM_CLKIN1, direction: OUTPUT}
  - {pin_num: '66', peripheral: GPIOB, signal: 'GPIO, 20', pin_signal: LCD_P16/PTB20/CMP0_OUT/LCD_P16_Fault, direction: OUTPUT}
  - {pin_num: '21', peripheral: GPIOE, signal: 'GPIO, 23', pin_signal: ADC0_DM3/ADC0_SE7a/PTE23/TPM2_CH1/UART2_RX, direction: OUTPUT}
  - {pin_num: '19', peripheral: GPIOE, signal: 'GPIO, 21', pin_signal: LCD_P60/ADC0_DM0/ADC0_SE4a/PTE21/TPM1_CH1/UART0_RX/LCD_P60_Fault, direction: OUTPUT}
  - {pin_num: '64', peripheral: GPIOB, signal: 'GPIO, 18', pin_signal: LCD_P14/TSI0_CH11/PTB18/TPM2_CH0/I2S0_TX_BCLK/LCD_P14_Fault, direction: OUTPUT}
  - {pin_num: '65', peripheral: GPIOB, signal: 'GPIO, 19', pin_signal: LCD_P15/TSI0_CH12/PTB19/TPM2_CH1/I2S0_TX_FS/LCD_P15_Fault, direction: OUTPUT}
  - {pin_num: '70', peripheral: GPIOC, signal: 'GPIO, 0', pin_signal: LCD_P20/ADC0_SE14/TSI0_CH13/PTC0/EXTRG_IN/USB_SOF_OUT/CMP0_OUT/I2S0_TXD0/LCD_P20_Fault, direction: OUTPUT}
  - {pin_num: '80', peripheral: GPIOC, signal: 'GPIO, 4', pin_signal: LCD_P24/PTC4/LLWU_P8/SPI0_PCS0/UART1_TX/TPM0_CH3/I2S0_MCLK/LCD_P24_Fault, direction: OUTPUT,
    slew_rate: slow}
  - {pin_num: '82', peripheral: GPIOC, signal: 'GPIO, 6', pin_signal: LCD_P26/CMP0_IN0/PTC6/LLWU_P10/SPI0_MOSI/EXTRG_IN/I2S0_RX_BCLK/SPI0_MISO/I2S0_MCLK/LCD_P26_Fault,
    direction: OUTPUT, slew_rate: slow}
  - {pin_num: '83', peripheral: GPIOC, signal: 'GPIO, 7', pin_signal: LCD_P27/CMP0_IN1/PTC7/SPI0_MISO/USB_SOF_OUT/I2S0_RX_FS/SPI0_MOSI/LCD_P27_Fault, direction: OUTPUT,
    slew_rate: slow}
  - {pin_num: '86', peripheral: GPIOC, signal: 'GPIO, 10', pin_signal: LCD_P30/PTC10/I2C1_SCL/I2S0_RX_FS/LCD_P30_Fault, direction: OUTPUT}
  - {pin_num: '87', peripheral: GPIOC, signal: 'GPIO, 11', pin_signal: LCD_P31/PTC11/I2C1_SDA/I2S0_RXD0/LCD_P31_Fault, direction: OUTPUT}
  - {pin_num: '3', peripheral: GPIOE, signal: 'GPIO, 2', pin_signal: LCD_P50/PTE2/SPI1_SCK/LCD_P50_Fault, direction: INPUT}
  - {pin_num: '4', peripheral: GPIOE, signal: 'GPIO, 3', pin_signal: LCD_P51/PTE3/SPI1_MISO/SPI1_MOSI/LCD_P51_Fault, direction: INPUT}
  - {pin_num: '7', peripheral: GPIOE, signal: 'GPIO, 6', pin_signal: LCD_P54/PTE6/I2S0_MCLK/USB_SOF_OUT/LCD_P54_Fault, direction: INPUT}
  - {pin_num: '14', peripheral: GPIOE, signal: 'GPIO, 16', pin_signal: LCD_P55/ADC0_DP1/ADC0_SE1/PTE16/SPI0_PCS0/UART2_TX/TPM_CLKIN0/LCD_P55_Fault, direction: INPUT,
    slew_rate: slow}
  - {pin_num: '15', peripheral: GPIOE, signal: 'GPIO, 17', pin_signal: LCD_P56/ADC0_DM1/ADC0_SE5a/PTE17/SPI0_SCK/UART2_RX/TPM_CLKIN1/LPTMR0_ALT3/LCD_P56_Fault, direction: INPUT,
    slew_rate: slow}
  - {pin_num: '16', peripheral: GPIOE, signal: 'GPIO, 18', pin_signal: LCD_P57/ADC0_DP2/ADC0_SE2/PTE18/SPI0_MOSI/I2C0_SDA/SPI0_MISO/LCD_P57_Fault, direction: INPUT,
    slew_rate: slow}
  - {pin_num: '17', peripheral: GPIOE, signal: 'GPIO, 19', pin_signal: LCD_P58/ADC0_DM2/ADC0_SE6a/PTE19/SPI0_MISO/I2C0_SCL/SPI0_MOSI/LCD_P58_Fault, direction: INPUT,
    slew_rate: slow}
  - {pin_num: '28', peripheral: GPIOE, signal: 'GPIO, 31', pin_signal: PTE31/TPM0_CH4, direction: INPUT}
  - {pin_num: '1', peripheral: UART1, signal: TX, pin_signal: LCD_P48/PTE0/SPI1_MISO/UART1_TX/RTC_CLKOUT/CMP0_OUT/I2C1_SDA/LCD_P48_Fault}
  - {pin_num: '2', peripheral: UART1, signal: RX, pin_signal: LCD_P49/PTE1/SPI1_MOSI/UART1_RX/SPI1_MISO/I2C1_SCL/LCD_P49_Fault}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Port A Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Port B Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortB);
    /* Port C Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortC);
    /* Port D Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortD);
    /* Port E Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortE);

    gpio_pin_config_t T8_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA1 (pin 35)  */
    GPIO_PinInit(BOARD_INITPINS_T8_GPIO, BOARD_INITPINS_T8_PIN, &T8_config);

    gpio_pin_config_t T7_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA2 (pin 36)  */
    GPIO_PinInit(BOARD_INITPINS_T7_GPIO, BOARD_INITPINS_T7_PIN, &T7_config);

    gpio_pin_config_t T4_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA4 (pin 38)  */
    GPIO_PinInit(BOARD_INITPINS_T4_GPIO, BOARD_INITPINS_T4_PIN, &T4_config);

    gpio_pin_config_t T3_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA5 (pin 39)  */
    GPIO_PinInit(BOARD_INITPINS_T3_GPIO, BOARD_INITPINS_T3_PIN, &T3_config);

    gpio_pin_config_t RS_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA7 (pin 41)  */
    GPIO_PinInit(BOARD_INITPINS_RS_GPIO, BOARD_INITPINS_RS_PIN, &RS_config);

    gpio_pin_config_t T5_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA12 (pin 42)  */
    GPIO_PinInit(BOARD_INITPINS_T5_GPIO, BOARD_INITPINS_T5_PIN, &T5_config);

    gpio_pin_config_t S8_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB18 (pin 64)  */
    GPIO_PinInit(BOARD_INITPINS_S8_GPIO, BOARD_INITPINS_S8_PIN, &S8_config);

    gpio_pin_config_t S7_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB19 (pin 65)  */
    GPIO_PinInit(BOARD_INITPINS_S7_GPIO, BOARD_INITPINS_S7_PIN, &S7_config);

    gpio_pin_config_t D6_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTB20 (pin 66)  */
    GPIO_PinInit(BOARD_INITPINS_D6_GPIO, BOARD_INITPINS_D6_PIN, &D6_config);

    gpio_pin_config_t S6_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC0 (pin 70)  */
    GPIO_PinInit(BOARD_INITPINS_S6_GPIO, BOARD_INITPINS_S6_PIN, &S6_config);

    gpio_pin_config_t S5_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC4 (pin 80)  */
    GPIO_PinInit(BOARD_INITPINS_S5_GPIO, BOARD_INITPINS_S5_PIN, &S5_config);

    gpio_pin_config_t S4_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC6 (pin 82)  */
    GPIO_PinInit(BOARD_INITPINS_S4_GPIO, BOARD_INITPINS_S4_PIN, &S4_config);

    gpio_pin_config_t S3_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC7 (pin 83)  */
    GPIO_PinInit(BOARD_INITPINS_S3_GPIO, BOARD_INITPINS_S3_PIN, &S3_config);

    gpio_pin_config_t T1_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC9 (pin 85)  */
    GPIO_PinInit(BOARD_INITPINS_T1_GPIO, BOARD_INITPINS_T1_PIN, &T1_config);

    gpio_pin_config_t S2_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC10 (pin 86)  */
    GPIO_PinInit(BOARD_INITPINS_S2_GPIO, BOARD_INITPINS_S2_PIN, &S2_config);

    gpio_pin_config_t S1_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC11 (pin 87)  */
    GPIO_PinInit(BOARD_INITPINS_S1_GPIO, BOARD_INITPINS_S1_PIN, &S1_config);

    gpio_pin_config_t E_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC13 (pin 89)  */
    GPIO_PinInit(BOARD_INITPINS_E_GPIO, BOARD_INITPINS_E_PIN, &E_config);

    gpio_pin_config_t RW_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC16 (pin 90)  */
    GPIO_PinInit(BOARD_INITPINS_RW_GPIO, BOARD_INITPINS_RW_PIN, &RW_config);

    gpio_pin_config_t T2_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC18 (pin 92)  */
    GPIO_PinInit(BOARD_INITPINS_T2_GPIO, BOARD_INITPINS_T2_PIN, &T2_config);

    gpio_pin_config_t T6_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD3 (pin 96)  */
    GPIO_PinInit(BOARD_INITPINS_T6_GPIO, BOARD_INITPINS_T6_PIN, &T6_config);

    gpio_pin_config_t E8_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTE2 (pin 3)  */
    GPIO_PinInit(BOARD_INITPINS_E8_GPIO, BOARD_INITPINS_E8_PIN, &E8_config);

    gpio_pin_config_t E7_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTE3 (pin 4)  */
    GPIO_PinInit(BOARD_INITPINS_E7_GPIO, BOARD_INITPINS_E7_PIN, &E7_config);

    gpio_pin_config_t E6_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTE6 (pin 7)  */
    GPIO_PinInit(BOARD_INITPINS_E6_GPIO, BOARD_INITPINS_E6_PIN, &E6_config);

    gpio_pin_config_t E5_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTE16 (pin 14)  */
    GPIO_PinInit(BOARD_INITPINS_E5_GPIO, BOARD_INITPINS_E5_PIN, &E5_config);

    gpio_pin_config_t E4_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTE17 (pin 15)  */
    GPIO_PinInit(BOARD_INITPINS_E4_GPIO, BOARD_INITPINS_E4_PIN, &E4_config);

    gpio_pin_config_t E3_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTE18 (pin 16)  */
    GPIO_PinInit(BOARD_INITPINS_E3_GPIO, BOARD_INITPINS_E3_PIN, &E3_config);

    gpio_pin_config_t E2_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTE19 (pin 17)  */
    GPIO_PinInit(BOARD_INITPINS_E2_GPIO, BOARD_INITPINS_E2_PIN, &E2_config);

    gpio_pin_config_t D4_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTE21 (pin 19)  */
    GPIO_PinInit(BOARD_INITPINS_D4_GPIO, BOARD_INITPINS_D4_PIN, &D4_config);

    gpio_pin_config_t D5_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTE23 (pin 21)  */
    GPIO_PinInit(BOARD_INITPINS_D5_GPIO, BOARD_INITPINS_D5_PIN, &D5_config);

    gpio_pin_config_t D7_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTE30 (pin 27)  */
    GPIO_PinInit(BOARD_INITPINS_D7_GPIO, BOARD_INITPINS_D7_PIN, &D7_config);

    gpio_pin_config_t E1_config = {
        .pinDirection = kGPIO_DigitalInput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTE31 (pin 28)  */
    GPIO_PinInit(BOARD_INITPINS_E1_GPIO, BOARD_INITPINS_E1_PIN, &E1_config);

    /* PORTA1 (pin 35) is configured as PTA1 */
    PORT_SetPinMux(BOARD_INITPINS_T8_PORT, BOARD_INITPINS_T8_PIN, kPORT_MuxAsGpio);

    /* PORTA12 (pin 42) is configured as PTA12 */
    PORT_SetPinMux(BOARD_INITPINS_T5_PORT, BOARD_INITPINS_T5_PIN, kPORT_MuxAsGpio);

    /* PORTA2 (pin 36) is configured as PTA2 */
    PORT_SetPinMux(BOARD_INITPINS_T7_PORT, BOARD_INITPINS_T7_PIN, kPORT_MuxAsGpio);

    /* PORTA4 (pin 38) is configured as PTA4 */
    PORT_SetPinMux(BOARD_INITPINS_T4_PORT, BOARD_INITPINS_T4_PIN, kPORT_MuxAsGpio);

    /* PORTA5 (pin 39) is configured as PTA5 */
    PORT_SetPinMux(BOARD_INITPINS_T3_PORT, BOARD_INITPINS_T3_PIN, kPORT_MuxAsGpio);

    /* PORTA7 (pin 41) is configured as PTA7 */
    PORT_SetPinMux(BOARD_INITPINS_RS_PORT, BOARD_INITPINS_RS_PIN, kPORT_MuxAsGpio);

    /* PORTB18 (pin 64) is configured as PTB18 */
    PORT_SetPinMux(BOARD_INITPINS_S8_PORT, BOARD_INITPINS_S8_PIN, kPORT_MuxAsGpio);

    /* PORTB19 (pin 65) is configured as PTB19 */
    PORT_SetPinMux(BOARD_INITPINS_S7_PORT, BOARD_INITPINS_S7_PIN, kPORT_MuxAsGpio);

    /* PORTB20 (pin 66) is configured as PTB20 */
    PORT_SetPinMux(BOARD_INITPINS_D6_PORT, BOARD_INITPINS_D6_PIN, kPORT_MuxAsGpio);

    /* PORTC0 (pin 70) is configured as PTC0 */
    PORT_SetPinMux(BOARD_INITPINS_S6_PORT, BOARD_INITPINS_S6_PIN, kPORT_MuxAsGpio);

    /* PORTC10 (pin 86) is configured as PTC10 */
    PORT_SetPinMux(BOARD_INITPINS_S2_PORT, BOARD_INITPINS_S2_PIN, kPORT_MuxAsGpio);

    /* PORTC11 (pin 87) is configured as PTC11 */
    PORT_SetPinMux(BOARD_INITPINS_S1_PORT, BOARD_INITPINS_S1_PIN, kPORT_MuxAsGpio);

    /* PORTC13 (pin 89) is configured as PTC13 */
    PORT_SetPinMux(BOARD_INITPINS_E_PORT, BOARD_INITPINS_E_PIN, kPORT_MuxAsGpio);

    /* PORTC16 (pin 90) is configured as PTC16 */
    PORT_SetPinMux(BOARD_INITPINS_RW_PORT, BOARD_INITPINS_RW_PIN, kPORT_MuxAsGpio);

    /* PORTC18 (pin 92) is configured as PTC18 */
    PORT_SetPinMux(BOARD_INITPINS_T2_PORT, BOARD_INITPINS_T2_PIN, kPORT_MuxAsGpio);

    /* PORTC4 (pin 80) is configured as PTC4 */
    PORT_SetPinMux(BOARD_INITPINS_S5_PORT, BOARD_INITPINS_S5_PIN, kPORT_MuxAsGpio);

    PORTC->PCR[4] = ((PORTC->PCR[4] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_SRE_MASK | PORT_PCR_ISF_MASK)))

                     /* Slew Rate Enable: Slow slew rate is configured on the corresponding pin, if the pin is
                      * configured as a digital output. */
                     | PORT_PCR_SRE(kPORT_SlowSlewRate));

    /* PORTC6 (pin 82) is configured as PTC6 */
    PORT_SetPinMux(BOARD_INITPINS_S4_PORT, BOARD_INITPINS_S4_PIN, kPORT_MuxAsGpio);

    PORTC->PCR[6] = ((PORTC->PCR[6] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_SRE_MASK | PORT_PCR_ISF_MASK)))

                     /* Slew Rate Enable: Slow slew rate is configured on the corresponding pin, if the pin is
                      * configured as a digital output. */
                     | PORT_PCR_SRE(kPORT_SlowSlewRate));

    /* PORTC7 (pin 83) is configured as PTC7 */
    PORT_SetPinMux(BOARD_INITPINS_S3_PORT, BOARD_INITPINS_S3_PIN, kPORT_MuxAsGpio);

    PORTC->PCR[7] = ((PORTC->PCR[7] &
                      /* Mask bits to zero which are setting */
                      (~(PORT_PCR_SRE_MASK | PORT_PCR_ISF_MASK)))

                     /* Slew Rate Enable: Slow slew rate is configured on the corresponding pin, if the pin is
                      * configured as a digital output. */
                     | PORT_PCR_SRE(kPORT_SlowSlewRate));

    /* PORTC9 (pin 85) is configured as PTC9 */
    PORT_SetPinMux(BOARD_INITPINS_T1_PORT, BOARD_INITPINS_T1_PIN, kPORT_MuxAsGpio);

    /* PORTD3 (pin 96) is configured as PTD3 */
    PORT_SetPinMux(BOARD_INITPINS_T6_PORT, BOARD_INITPINS_T6_PIN, kPORT_MuxAsGpio);

    /* PORTE0 (pin 1) is configured as UART1_TX */
    PORT_SetPinMux(BOARD_INITPINS_TX_PORT, BOARD_INITPINS_TX_PIN, kPORT_MuxAlt3);

    /* PORTE1 (pin 2) is configured as UART1_RX */
    PORT_SetPinMux(BOARD_INITPINS_RX_PORT, BOARD_INITPINS_RX_PIN, kPORT_MuxAlt3);

    /* PORTE16 (pin 14) is configured as PTE16 */
    PORT_SetPinMux(BOARD_INITPINS_E5_PORT, BOARD_INITPINS_E5_PIN, kPORT_MuxAsGpio);

    PORTE->PCR[16] = ((PORTE->PCR[16] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_SRE_MASK | PORT_PCR_ISF_MASK)))

                      /* Slew Rate Enable: Slow slew rate is configured on the corresponding pin, if the pin is
                       * configured as a digital output. */
                      | PORT_PCR_SRE(kPORT_SlowSlewRate));

    /* PORTE17 (pin 15) is configured as PTE17 */
    PORT_SetPinMux(BOARD_INITPINS_E4_PORT, BOARD_INITPINS_E4_PIN, kPORT_MuxAsGpio);

    PORTE->PCR[17] = ((PORTE->PCR[17] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_SRE_MASK | PORT_PCR_ISF_MASK)))

                      /* Slew Rate Enable: Slow slew rate is configured on the corresponding pin, if the pin is
                       * configured as a digital output. */
                      | PORT_PCR_SRE(kPORT_SlowSlewRate));

    /* PORTE18 (pin 16) is configured as PTE18 */
    PORT_SetPinMux(BOARD_INITPINS_E3_PORT, BOARD_INITPINS_E3_PIN, kPORT_MuxAsGpio);

    PORTE->PCR[18] = ((PORTE->PCR[18] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_SRE_MASK | PORT_PCR_ISF_MASK)))

                      /* Slew Rate Enable: Slow slew rate is configured on the corresponding pin, if the pin is
                       * configured as a digital output. */
                      | PORT_PCR_SRE(kPORT_SlowSlewRate));

    /* PORTE19 (pin 17) is configured as PTE19 */
    PORT_SetPinMux(BOARD_INITPINS_E2_PORT, BOARD_INITPINS_E2_PIN, kPORT_MuxAsGpio);

    PORTE->PCR[19] = ((PORTE->PCR[19] &
                       /* Mask bits to zero which are setting */
                       (~(PORT_PCR_SRE_MASK | PORT_PCR_ISF_MASK)))

                      /* Slew Rate Enable: Slow slew rate is configured on the corresponding pin, if the pin is
                       * configured as a digital output. */
                      | PORT_PCR_SRE(kPORT_SlowSlewRate));

    /* PORTE2 (pin 3) is configured as PTE2 */
    PORT_SetPinMux(BOARD_INITPINS_E8_PORT, BOARD_INITPINS_E8_PIN, kPORT_MuxAsGpio);

    /* PORTE21 (pin 19) is configured as PTE21 */
    PORT_SetPinMux(BOARD_INITPINS_D4_PORT, BOARD_INITPINS_D4_PIN, kPORT_MuxAsGpio);

    /* PORTE23 (pin 21) is configured as PTE23 */
    PORT_SetPinMux(BOARD_INITPINS_D5_PORT, BOARD_INITPINS_D5_PIN, kPORT_MuxAsGpio);

    /* PORTE3 (pin 4) is configured as PTE3 */
    PORT_SetPinMux(BOARD_INITPINS_E7_PORT, BOARD_INITPINS_E7_PIN, kPORT_MuxAsGpio);

    /* PORTE30 (pin 27) is configured as PTE30 */
    PORT_SetPinMux(BOARD_INITPINS_D7_PORT, BOARD_INITPINS_D7_PIN, kPORT_MuxAsGpio);

    /* PORTE31 (pin 28) is configured as PTE31 */
    PORT_SetPinMux(BOARD_INITPINS_E1_PORT, BOARD_INITPINS_E1_PIN, kPORT_MuxAsGpio);

    /* PORTE6 (pin 7) is configured as PTE6 */
    PORT_SetPinMux(BOARD_INITPINS_E6_PORT, BOARD_INITPINS_E6_PIN, kPORT_MuxAsGpio);

    SIM->SOPT5 = ((SIM->SOPT5 &
                   /* Mask bits to zero which are setting */
                   (~(SIM_SOPT5_UART1TXSRC_MASK | SIM_SOPT5_UART1RXSRC_MASK)))

                  /* UART1 Transmit Data Source Select: UART1_TX pin. */
                  | SIM_SOPT5_UART1TXSRC(SOPT5_UART1TXSRC_UART_TX)

                  /* UART1 Receive Data Source Select: UART1_RX pin. */
                  | SIM_SOPT5_UART1RXSRC(SOPT5_UART1RXSRC_UART_RX));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
